[project]
name = "gl2s3ig"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lark>=1.3.0",
    "pydantic>=2.12.3",
    "pyyaml>=6.0.3",
]
